# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15

[cpu_usage]
command=/home/lewin/.config/i3/scripts/cpu_usage/cpu_usage
label=CPU 
interval=10

[memory]
command=/home/lewin/.config/i3/scripts/memory/memory
label=MEM 
interval=30

[temperature]
command=/home/lewin/.config/i3/scripts/temperature/temperature
label=TEMP 
interval=10

[volume-pulseaudio]
command=/home/lewin/.config/i3/scripts/volume-pulseaudio/volume-pulseaudio
interval=once
signal=1
LONG_FORMAT="VOL ${VOL}%"
MUTED_COLOR="#a0a0a0"

[battery]
command=/home/lewin/.config/i3/scripts/battery/battery
interval=30
label=BAT 

[disk]
command=/home/lewin/.config/i3/scripts/disk/disk
label=HOME 
interval=30

[iface]
command=/home/lewin/.config/i3/scripts/iface/iface
interval=10

[arch-update]
command=/home/lewin/.config/i3/scripts/arch-update/arch-update
interval=3600
markup=pango
quiet=true
watch=^linux.* ^pacman.*
aur=true

[time]
command=date '+%a %d %b %Y %r '
interval=1

[keyindicator]
command=/home/lewin/.config/i3/scripts/keyindicator/keyindicator
KEY=CAPS
markup=pango
interval=once
signal=11
HIDE_WHEN_OFF=1
