asterisk= "# ";
font = "Roboto Mono:pixelsize=16";
bottom = true;
normal_fg = "#c5c8c6";
normal_bg = "#1d1f21";
prompt_fg = "#1d1f21";
prompt_bg = "#fba922";
desc_fg = "#1d1f21";
desc_bg = "#fba922";
