# Backend
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = false;
use-damage = true;

# Shadows
shadow = true;
shadow-radius = 15;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.6;
shadow-exclude = [
    "class_g = 'Brave-browser' && argb",
    "window_type = 'dock'"
];

# Opacity
inactive-opacity = 1;
blur-background = false;
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
opacity-rule = [
  "90:class_g = 'neomutt'",
  "90:class_g = 'newsboat'",
  "90:class_g = 'ncmpcpp'",
  "90:class_g = 'irssi'",
  "90:class_g = 'gcalcli'"
];

# Fading
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Other
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
sw-opti = false;
unredir-if-possible = false;
detect-transient = true;
detect-client-leader = true;

# Window type settings
wintypes:
{
    tooltip =
    {
        fade = true;
        shadow = false;
        opacity = 0.75;
        focus = true;
	full-shadow = false;
    };
};

# Use X Sync fence to sync clients' draw calls. Needed on nvidia-drivers with GLX backend for some users.
xrender-sync-fence = true;
