#! /bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          30
bspc config top_padding		-30

bspc config split_ratio          0.5
bspc config single_monocle	 true
bspc config borderless_monocle   true

bspc rule -a St desktop='I' follow=on state=pseudo_tiled
bspc rule -a Brave-browser desktop='II' follow=on
bspc rule -a neomutt desktop='III' follow=on
bspc rule -a ncmpcpp desktop='IV' follow=on state=pseudo_tiled
bspc rule -a newsboat desktop='V' follow=on state=pseudo_tiled
bspc rule -a irssi desktop='VI' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a pulsemixer state=pseudo_tiled
bspc rule -a youtube state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Sxiv state=pseudo_tiled

# polybar
launch_polybar &
podentr &
